from schemas.blog.scripts.main import BLOG_SCHEMA_SCRIPT_PATH_SQLITE
from schemas.blog.scripts.main import BLOG_SCHEMA_SCRIPT_PATH_MSSQL
from schemas.blog.scripts.main import BLOG_SCHEMA_SCRIPT_PATH_POSTGRESQL
