from stencil.blog.schemas.main import BLOG_SCHEMA_SCRIPT_PATH_MSSQL
from stencil.blog.schemas.main import BLOG_SCHEMA_SCRIPT_PATH_SQLITE
from stencil.blog.schemas.main import BLOG_SCHEMA_SCRIPT_PATH_POSTGRESQL
